/* The following code was generated by JFlex 1.7.0 */

package scanner;    /* Declares this class to be a part of the scanner package */

/**
* @author Maxwell Herron
* The purpose of this program is to generate a java scanner that will be able to 
* distinguish between words and numbers.
*/

/* Declarations */


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Scanner.jflex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\1\1\2\1\2\1\2\22\0\1\4\1\16\4\0"+
    "\1\20\1\0\1\15\1\15\1\14\1\10\1\0\1\5\1\13\1\12"+
    "\12\11\1\15\1\15\1\16\1\17\1\16\2\0\4\3\1\7\25\3"+
    "\1\15\1\0\1\15\3\0\1\24\1\3\1\22\1\40\1\34\1\31"+
    "\1\42\1\23\1\26\2\3\1\32\1\43\1\27\1\33\1\37\1\3"+
    "\1\25\1\35\1\30\1\41\1\3\1\36\3\3\1\15\1\21\1\15"+
    "\7\0\1\2\u05da\0\12\6\206\0\12\6\306\0\12\6\u019c\0\12\6"+
    "\166\0\12\6\166\0\12\6\166\0\12\6\166\0\12\6\166\0\12\6"+
    "\166\0\12\6\166\0\12\6\166\0\12\6\166\0\12\6\140\0\12\6"+
    "\166\0\12\6\106\0\12\6\u0116\0\12\6\106\0\12\6\u0746\0\12\6"+
    "\46\0\12\6\u012c\0\12\6\200\0\12\6\246\0\12\6\6\0\12\6"+
    "\266\0\12\6\126\0\12\6\206\0\12\6\6\0\12\6\u03ce\0\1\2"+
    "\1\2\u85f6\0\12\6\u02a6\0\12\6\46\0\12\6\306\0\12\6\26\0"+
    "\12\6\126\0\12\6\u0196\0\12\6\u5316\0\12\6\u0586\0\12\6\u0bbc\0"+
    "\12\6\200\0\12\6\74\0\12\6\220\0\12\6\u0116\0\12\6\u0156\0"+
    "\12\6\166\0\12\6\u0176\0\12\6\146\0\12\6\146\0\12\6\u01a6\0"+
    "\12\6\u0366\0\12\6\u4e06\0\12\6\346\0\12\6\u6c74\0\62\6\u1150\0"+
    "\12\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u16b5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\2\4\2\6"+
    "\2\1\10\3\2\0\1\7\1\0\1\10\1\0\3\3"+
    "\1\6\6\3\1\0\1\5\3\0\10\3\1\0\1\7"+
    "\2\0\1\10\5\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\44\0\330"+
    "\0\44\0\374\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4"+
    "\0\u01f8\0\u021c\0\u0240\0\u0264\0\u0288\0\u02ac\0\u02d0\0\u02f4"+
    "\0\u0318\0\u033c\0\u0360\0\u0384\0\u03a8\0\154\0\u03cc\0\u03f0"+
    "\0\u0414\0\u0438\0\u045c\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510"+
    "\0\u0534\0\u0558\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630"+
    "\0\u0654\0\u0678\0\u0678\0\u069c\0\u06c0\0\u033c\0\u06e4\0\u0708"+
    "\0\u072c\0\u0750\0\u0774";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\4\1\3\1\5\1\6\1\4"+
    "\1\7\1\6\1\10\1\2\1\7\1\11\1\12\1\2"+
    "\1\13\1\14\1\15\2\4\1\16\1\17\2\4\1\20"+
    "\2\4\1\21\1\4\1\22\1\23\4\4\45\0\1\3"+
    "\2\0\1\3\42\0\1\4\3\0\1\4\1\0\1\24"+
    "\10\0\22\4\5\0\1\25\1\6\2\0\1\6\40\0"+
    "\1\6\1\26\1\0\1\6\1\0\1\27\20\0\1\26"+
    "\14\0\1\25\1\30\2\0\1\30\1\31\1\0\1\32"+
    "\46\0\1\11\44\0\1\11\44\0\1\11\25\0\1\4"+
    "\3\0\1\4\1\0\1\24\10\0\1\4\1\33\20\4"+
    "\3\0\1\4\3\0\1\4\1\0\1\24\10\0\12\4"+
    "\1\34\7\4\3\0\1\4\3\0\1\4\1\0\1\24"+
    "\10\0\5\4\1\35\1\4\1\36\12\4\3\0\1\4"+
    "\3\0\1\4\1\0\1\24\10\0\10\4\1\37\6\4"+
    "\1\40\2\4\3\0\1\4\3\0\1\4\1\0\1\24"+
    "\10\0\5\4\1\41\2\4\1\42\11\4\3\0\1\4"+
    "\3\0\1\4\1\0\1\24\10\0\1\4\1\43\20\4"+
    "\3\0\1\4\3\0\1\4\1\0\1\24\10\0\3\4"+
    "\1\44\16\4\11\0\1\24\40\0\1\30\2\0\1\30"+
    "\37\0\1\45\2\0\1\45\1\46\41\0\1\47\1\0"+
    "\1\27\22\0\1\47\15\0\1\30\1\50\1\0\1\30"+
    "\1\0\1\27\20\0\1\50\7\0\1\31\2\0\41\31"+
    "\14\32\1\51\27\32\3\0\1\4\3\0\1\4\1\0"+
    "\1\24\10\0\2\4\1\52\17\4\3\0\1\4\3\0"+
    "\1\4\1\0\1\24\10\0\2\4\1\41\3\4\1\53"+
    "\13\4\3\0\1\4\3\0\1\4\1\0\1\24\10\0"+
    "\6\4\1\36\13\4\3\0\1\4\3\0\1\4\1\0"+
    "\1\24\10\0\11\4\1\54\10\4\3\0\1\4\3\0"+
    "\1\4\1\0\1\24\10\0\5\4\1\55\14\4\3\0"+
    "\1\4\3\0\1\4\1\0\1\24\10\0\16\4\1\36"+
    "\3\4\3\0\1\4\3\0\1\4\1\0\1\24\10\0"+
    "\13\4\1\56\6\4\3\0\1\4\3\0\1\4\1\0"+
    "\1\24\10\0\4\4\1\57\15\4\3\0\1\4\3\0"+
    "\1\4\1\0\1\24\10\0\4\4\1\60\4\4\1\61"+
    "\10\4\11\0\1\46\43\0\1\46\1\0\1\27\35\0"+
    "\1\62\2\0\1\62\1\63\37\0\1\64\2\0\1\64"+
    "\1\65\32\0\12\32\1\66\1\32\1\51\27\32\3\0"+
    "\1\4\3\0\1\4\1\0\1\24\10\0\3\4\1\36"+
    "\16\4\3\0\1\4\3\0\1\4\1\0\1\24\10\0"+
    "\17\4\1\67\2\4\3\0\1\4\3\0\1\4\1\0"+
    "\1\24\10\0\2\4\1\35\17\4\3\0\1\4\3\0"+
    "\1\4\1\0\1\24\10\0\1\36\21\4\3\0\1\4"+
    "\3\0\1\4\1\0\1\24\10\0\12\4\1\36\7\4"+
    "\3\0\1\4\3\0\1\4\1\0\1\24\10\0\10\4"+
    "\1\56\11\4\3\0\1\4\3\0\1\4\1\0\1\24"+
    "\10\0\5\4\1\35\14\4\3\0\1\4\3\0\1\4"+
    "\1\0\1\24\10\0\20\4\1\70\1\4\11\0\1\63"+
    "\43\0\1\65\43\0\1\65\1\0\1\27\33\0\1\4"+
    "\3\0\1\4\1\0\1\24\10\0\3\4\1\71\16\4"+
    "\3\0\1\4\3\0\1\4\1\0\1\24\10\0\3\4"+
    "\1\72\16\4\3\0\1\4\3\0\1\4\1\0\1\24"+
    "\10\0\5\4\1\36\14\4\3\0\1\4\3\0\1\4"+
    "\1\0\1\24\10\0\2\4\1\73\17\4\3\0\1\4"+
    "\3\0\1\4\1\0\1\24\10\0\21\4\1\36";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1944];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\1\1\1\11\13\1\2\0"+
    "\1\1\1\0\1\1\1\0\12\1\1\0\1\1\3\0"+
    "\10\1\1\0\1\1\2\0\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    // Instantiating a LookupTable object
    LookupTable lookupTable = new LookupTable();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 374) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken() throws java.io.IOException, BadCharacterException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   return null;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { String errorMessage = "Illegal char: '" + yytext() + "' found.";
             throw new BadCharacterException(errorMessage);
            } 
            // fall through
          case 9: break;
          case 2: 
            { //System.out.println("Found whitespace!");
            } 
            // fall through
          case 10: break;
          case 3: 
            { Token t = new Token();
                        t.lexeme = yytext();
                        t.type = TokenType.IDENTIFIER;
                        System.out.println(t.toString());
                        return t;
            } 
            // fall through
          case 11: break;
          case 4: 
            { Token t = new Token();
				t.lexeme = yytext();
				t.type = lookupTable.get(t.lexeme);
				System.out.println(t.toString());
				return t;
            } 
            // fall through
          case 12: break;
          case 5: 
            { //System.out.println("Found a number: " + yytext());
			 Token t = new Token();
			 t.lexeme = yytext();
			 t.type = TokenType.NUMBER;
			 System.out.println(t.toString());
			 return t;
            } 
            // fall through
          case 13: break;
          case 6: 
            { Token t = new Token();
                t.lexeme = yytext();
                t.type = lookupTable.get(t.lexeme);
                System.out.println(t.toString());
                return t;
            } 
            // fall through
          case 14: break;
          case 7: 
            { Token t = new Token();
                    t.lexeme = yytext();
                    t.type = TokenType.REAL_NUMBER;
                    System.out.println(t.toString());
                    return t;
            } 
            // fall through
          case 15: break;
          case 8: 
            { Token t = new Token();
                t.lexeme = yytext();
                t.type = TokenType.COMMENT;
                System.out.println(t.toString());
                return t;
            } 
            // fall through
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
